class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'ar': {
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'phone': 'الهاتف',
      'medical_history': 'السجل الطبي',
      'visits': 'الزيارات',
      'balance': 'الرصيد',
      'add_visit': 'إضافة زيارة',
      'edit_visit': 'تعديل الزيارة',
      'follow_ups': 'المتابعات',
      'appointments': 'المواعيد',
      'edit': 'تعديل',
      'delete': 'حذف',
      'confirm_delete': 'تأكيد الحذف',
      'delete_visit_confirm': 'هل أنت متأكد من حذف هذه الزيارة؟',
      'add_appointment': 'إضافة موعد',
      'no_visits': 'لا توجد زيارات',
      'no_followups': 'لا توجد متابعات',
      'visit': 'زيارة',
      'date': 'التاريخ',
      'procedure': 'الإجراء',
      'procedure_treatment': 'الإجراء / العلاج',
      'price': 'السعر',
      'lab': 'المختبر',
      'lab_expense': 'تكلفة المختبر',
      'paid': 'المدفوع',
      'payment': 'الدفع',
      'payment_received': 'الدفعة المستلمة',
      'notes': 'ملاحظات',
      'no_appointments': 'لا توجد مواعيد',
      'save_visit': 'حفظ الزيارة',
      'time': 'الوقت',
      'status': 'الحالة',
      'discount': 'الخصم',
      'tooth_no': 'رقم السن',
      'plans': 'الخطط',
      'add_plan': 'إضافة خطة',
      'edit_plan': 'تعديل الخطة',
      'no_plans': 'لا توجد خطط علاجية',
      'plan_name': 'اسم الخطة',
      'goals': 'الأهداف',
      'estimated_cost': 'التكلفة المقدرة',
      'start_date': 'تاريخ البداية',
      'end_date': 'تاريخ الانتهاء',
      'delete_plan_confirm': 'حذف هذه الخطة العلاجية؟',
      'holidays': 'العطلات',
      'add_holiday': 'إضافة عطلة',
      'no_holidays': 'لا توجد عطلات',
      'holiday_name': 'الاسم (اختياري)',
      'delete_holiday_confirm': 'حذف هذه العطلة؟',
      'payment_history': 'سجل الدفعات',
      'statement': 'كشف الحساب',
      'print_statement': 'طباعة كشف الحساب',
      'description': 'الوصف',
      'subtotal': 'الإجمالي قبل الخصم',
      'total_to_pay': 'الإجمالي المطلوب',
      'left': 'المتبقي',
      'no_data': 'لا توجد بيانات',
      'patient': 'المريض',
      'images': 'الصور',
      'no_images': 'لا توجد صور طبية',
      'add_image': 'إضافة صورة',
      'take_photo': 'التقاط صورة',
      'pick_from_gallery': 'اختيار من المعرض',
      'image_synced': 'تمت المزامنة',
      'image_pending': 'بانتظار المزامنة',
      'delete_image_confirm': 'حذف هذه الصورة؟',
      'image_note_optional': 'ملاحظة (اختياري)',
      'sync_images_lan_only': 'تتم مزامنة الصور عبر الشبكة المحلية فقط',
    },
    'en': {
      'cancel': 'Cancel',
      'save': 'Save',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone': 'Phone',
      'medical_history': 'Medical History',
      'visits': 'Visits',
      'balance': 'Balance',
      'add_visit': 'Add Visit',
      'edit_visit': 'Edit Visit',
      'follow_ups': 'Follow-ups',
      'appointments': 'Appointments',
      'edit': 'Edit',
      'delete': 'Delete',
      'confirm_delete': 'Confirm Delete',
      'delete_visit_confirm': 'Are you sure you want to delete this visit?',
      'add_appointment': 'Add Appointment',
      'no_visits': 'No visits',
      'no_followups': 'No follow-up records yet',
      'visit': 'Visit',
      'date': 'Date',
      'procedure': 'Procedure',
      'procedure_treatment': 'Procedure / Treatment',
      'price': 'Price',
      'lab': 'Lab',
      'lab_expense': 'Lab Expense',
      'paid': 'Paid',
      'payment': 'Payment',
      'payment_received': 'Payment Received',
      'notes': 'Notes',
      'no_appointments': 'No appointments',
      'save_visit': 'Save Visit',
      'time': 'Time',
      'status': 'Status',
      'discount': 'Discount',
      'tooth_no': 'Tooth #',
      'plans': 'Plans',
      'add_plan': 'Add Plan',
      'edit_plan': 'Edit Plan',
      'no_plans': 'No treatment plans yet',
      'plan_name': 'Plan name',
      'goals': 'Goals',
      'estimated_cost': 'Estimated cost',
      'start_date': 'Start date',
      'end_date': 'End date',
      'delete_plan_confirm': 'Delete this treatment plan?',
      'holidays': 'Holidays',
      'add_holiday': 'Add holiday',
      'no_holidays': 'No holidays scheduled',
      'holiday_name': 'Name (optional)',
      'delete_holiday_confirm': 'Delete this holiday?',
      'payment_history': 'Payment history',
      'statement': 'Statement',
      'print_statement': 'Print / share statement',
      'description': 'Description',
      'subtotal': 'Subtotal',
      'total_to_pay': 'Total to Pay',
      'left': 'Left',
      'no_data': 'No data',
      'patient': 'Patient',
      'images': 'Images',
      'no_images': 'No medical images yet',
      'add_image': 'Add image',
      'take_photo': 'Take photo',
      'pick_from_gallery': 'Pick from gallery',
      'image_synced': 'Synced',
      'image_pending': 'Pending sync',
      'delete_image_confirm': 'Delete this image?',
      'image_note_optional': 'Note (optional)',
      'sync_images_lan_only': 'Images sync over local Wi-Fi only',
    }
  };

  static String t(String key, {bool isArabic = false}) {
    final lang = isArabic ? 'ar' : 'en';
    return translations[lang]?[key] ?? key;
  }
}
