class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'ar': {
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'phone': 'الهاتف',
      'medical_history': 'السجل الطبي',
      'visits': 'الزيارات',
      'balance': 'الرصيد',
      'add_visit': 'إضافة زيارة',
      'edit_visit': 'تعديل الزيارة',
      'follow_ups': 'المتابعات',
      'appointments': 'المواعيد',
      'edit': 'تعديل',
      'delete': 'حذف',
      'confirm_delete': 'تأكيد الحذف',
      'delete_visit_confirm': 'هل أنت متأكد من حذف هذه الزيارة؟',
      'add_appointment': 'إضافة موعد',
      'no_visits': 'لا توجد زيارات',
      'no_followups': 'لا توجد متابعات',
      'visit': 'زيارة',
      'date': 'التاريخ',
      'procedure': 'الإجراء',
      'procedure_treatment': 'الإجراء / العلاج',
      'price': 'السعر',
      'lab': 'المختبر',
      'lab_expense': 'تكلفة المختبر',
      'paid': 'المدفوع',
      'payment': 'الدفع',
      'payment_received': 'الدفعة المستلمة',
      'notes': 'ملاحظات',
      'no_appointments': 'لا توجد مواعيد',
      'save_visit': 'حفظ الزيارة',
      'time': 'الوقت',
      'status': 'الحالة',
      'discount': 'الخصم',
      'tooth_no': 'رقم السن',
      'plans': 'الخطط',
      'add_plan': 'إضافة خطة',
      'edit_plan': 'تعديل الخطة',
      'no_plans': 'لا توجد خطط علاجية',
      'plan_name': 'اسم الخطة',
      'goals': 'الأهداف',
      'estimated_cost': 'التكلفة المقدرة',
      'start_date': 'تاريخ البداية',
      'end_date': 'تاريخ الانتهاء',
      'delete_plan_confirm': 'حذف هذه الخطة العلاجية؟',
      'holidays': 'العطلات',
      'add_holiday': 'إضافة عطلة',
      'no_holidays': 'لا توجد عطلات',
      'holiday_name': 'الاسم (اختياري)',
      'delete_holiday_confirm': 'حذف هذه العطلة؟',
      'payment_history': 'سجل الدفعات',
      'statement': 'كشف الحساب',
      'print_statement': 'طباعة كشف الحساب',
      'description': 'الوصف',
      'subtotal': 'الإجمالي قبل الخصم',
      'total_to_pay': 'الإجمالي المطلوب',
      'left': 'المتبقي',
      'no_data': 'لا توجد بيانات',
      'patient': 'المريض',
      'images': 'الصور',
      'no_images': 'لا توجد صور طبية',
      'add_image': 'إضافة صورة',
      'take_photo': 'التقاط صورة',
      'pick_from_gallery': 'اختيار من المعرض',
      'image_synced': 'تمت المزامنة',
      'image_pending': 'بانتظار المزامنة',
      'delete_image_confirm': 'حذف هذه الصورة؟',
      'image_note_optional': 'ملاحظة (اختياري)',
      'sync_images_lan_only': 'تتم مزامنة الصور عبر الشبكة المحلية فقط',
      // ── Status badges ──
      'status_completed': 'مكتمل',
      'status_paid': 'مدفوع',
      'status_scheduled': 'مجدول',
      'status_partial': 'جزئي',
      'status_unpaid': 'غير مدفوع',
      'status_postponed': 'مؤجل',
      'status_cancelled': 'ملغى',
      'status_pending': 'قيد الانتظار',
      // ── Home / navigation ──
      'nav_dashboard': 'لوحة التحكم',
      'nav_patients': 'المرضى',
      'nav_financial': 'المالية',
      'nav_reports': 'التقارير',
      'settings': 'الإعدادات',
      'switch_to_light': 'التبديل إلى الوضع الفاتح',
      'switch_to_dark': 'التبديل إلى الوضع الداكن',
      'renew_by_prefix': 'جدِّد من تطبيق سطح المكتب قبل ',
      'dismiss': 'تجاهل',
      'view_only_renew': 'وضع العرض فقط — اطلب من العيادة التجديد',
      'activate_on_desktop_title': 'فعِّل من تطبيق سطح المكتب أولاً',
      'activate_on_desktop_body': 'افتح تطبيق العيادة على سطح المكتب وأكمل التفعيل.',
      // ── Dashboard ──
      'total_patients': 'إجمالي المرضى',
      'todays_appointments': 'مواعيد اليوم',
      'total_visits': 'إجمالي الزيارات',
      'revenue': 'الإيرادات',
      'recent_appointments': 'أحدث المواعيد',
      'no_appointments_yet': 'لا توجد مواعيد بعد.\nأضف موعدًا للبدء.',
      // ── Patients ──
      'search_patients_hint': 'ابحث بالاسم أو الهاتف أو البريد…',
      'no_patients_found': 'لا يوجد مرضى',
      'add_patient': 'إضافة مريض',
      'delete_patient': 'حذف المريض',
      'cannot_be_undone': 'لا يمكن التراجع عن هذا الإجراء.',
      'unable_to_load_patients': 'تعذّر تحميل المرضى الآن',
      'possible_duplicate': 'احتمال تكرار',
      'duplicate_exists_prefix': 'يوجد مريض بنفس ',
      'duplicate_exists_suffix': ' بالفعل. هل تريد الحفظ على أي حال؟',
      'dup_reason_phone': 'الهاتف',
      'dup_reason_name': 'الاسم',
      'save_anyway': 'حفظ على أي حال',
      'email': 'البريد الإلكتروني',
      'date_of_birth': 'تاريخ الميلاد',
      'tap_to_pick_date': 'اضغط لاختيار التاريخ',
      'enter_valid_date': 'أدخل تاريخًا صحيحًا',
      'address': 'العنوان',
      'save_patient': 'حفظ المريض',
      'required': 'مطلوب',
      // ── Payment history ──
      'payments': 'الدفعات',
      'no_payments_recorded': 'لا توجد دفعات مسجلة',
      'followup': 'متابعة',
      'billing': 'فوترة',
      'billing_record': 'سجل فوترة',
      'credit': 'رصيد',
      'total_collected': 'إجمالي المُحصّل',
      // ── Reports ──
      'weekly': 'أسبوعي',
      'monthly': 'شهري',
      'no_data_yet': 'لا توجد بيانات بعد',
      'distinct_teeth': 'الأسنان المعالجة',
      'expenses': 'المصروفات',
      'profit': 'الربح',
      'last_6_months': 'آخر 6 أشهر',
      'latest_prefix': 'الأحدث: ',
      // ── Financial ──
      'receivables': 'الذمم',
      'unable_to_load_billing': 'تعذّر تحميل سجلات الفوترة الآن',
      'billing_saved': 'تم حفظ سجل الفوترة',
      'billing_deleted': 'تم حذف سجل الفوترة',
      'delete_billing': 'حذف سجل الفوترة',
      'delete_billing_q': 'حذف سجل الفوترة؟',
      'delete_billing_credit_prefix': 'سيعيد هذا أيضًا ',
      'delete_billing_credit_suffix':
          ' من الرصيد المطبَّق إلى المريض. حذف سجل الفوترة؟',
      'add_billing': 'إضافة فاتورة',
      'billed': 'المُفوتَر',
      'open': 'مفتوحة',
      'search_billing': 'ابحث في سجلات الفوترة',
      'all': 'الكل',
      'no_billing_records': 'لا توجد سجلات فوترة بعد',
      'no_records_match': 'لا توجد سجلات مطابقة للفلاتر',
      'add_record': 'إضافة سجل',
      'no_payment_date': 'لا يوجد تاريخ دفع',
      'credit_applied': 'الرصيد المطبَّق',
      'today': 'اليوم',
      'month': 'الشهر',
      'total_expenses': 'إجمالي المصروفات',
      'no_expenses_found': 'لا توجد مصروفات',
      'add_expense': 'إضافة مصروف',
      'no_outstanding': 'لا توجد أرصدة مستحقة',
      'total_receivables': 'إجمالي الذمم',
      'patients_label': 'مرضى',
      'total': 'الإجمالي',
      'last_payment': 'آخر دفعة',
      'amount': 'المبلغ',
      'amount_paid': 'المبلغ المدفوع',
      'use_credit': 'استخدام الرصيد',
      'available': 'المتاح',
      'payment_method': 'طريقة الدفع',
      'method_cash': 'نقدًا',
      'method_card': 'بطاقة',
      'method_bank_transfer': 'تحويل بنكي',
      'method_insurance': 'تأمين',
      'category': 'الفئة',
      'vendor_optional': 'المورّد (اختياري)',
      'save_expense': 'حفظ المصروف',
    },
    'en': {
      'cancel': 'Cancel',
      'save': 'Save',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone': 'Phone',
      'medical_history': 'Medical History',
      'visits': 'Visits',
      'balance': 'Balance',
      'add_visit': 'Add Visit',
      'edit_visit': 'Edit Visit',
      'follow_ups': 'Follow-ups',
      'appointments': 'Appointments',
      'edit': 'Edit',
      'delete': 'Delete',
      'confirm_delete': 'Confirm Delete',
      'delete_visit_confirm': 'Are you sure you want to delete this visit?',
      'add_appointment': 'Add Appointment',
      'no_visits': 'No visits',
      'no_followups': 'No follow-up records yet',
      'visit': 'Visit',
      'date': 'Date',
      'procedure': 'Procedure',
      'procedure_treatment': 'Procedure / Treatment',
      'price': 'Price',
      'lab': 'Lab',
      'lab_expense': 'Lab Expense',
      'paid': 'Paid',
      'payment': 'Payment',
      'payment_received': 'Payment Received',
      'notes': 'Notes',
      'no_appointments': 'No appointments',
      'save_visit': 'Save Visit',
      'time': 'Time',
      'status': 'Status',
      'discount': 'Discount',
      'tooth_no': 'Tooth #',
      'plans': 'Plans',
      'add_plan': 'Add Plan',
      'edit_plan': 'Edit Plan',
      'no_plans': 'No treatment plans yet',
      'plan_name': 'Plan name',
      'goals': 'Goals',
      'estimated_cost': 'Estimated cost',
      'start_date': 'Start date',
      'end_date': 'End date',
      'delete_plan_confirm': 'Delete this treatment plan?',
      'holidays': 'Holidays',
      'add_holiday': 'Add holiday',
      'no_holidays': 'No holidays scheduled',
      'holiday_name': 'Name (optional)',
      'delete_holiday_confirm': 'Delete this holiday?',
      'payment_history': 'Payment history',
      'statement': 'Statement',
      'print_statement': 'Print / share statement',
      'description': 'Description',
      'subtotal': 'Subtotal',
      'total_to_pay': 'Total to Pay',
      'left': 'Left',
      'no_data': 'No data',
      'patient': 'Patient',
      'images': 'Images',
      'no_images': 'No medical images yet',
      'add_image': 'Add image',
      'take_photo': 'Take photo',
      'pick_from_gallery': 'Pick from gallery',
      'image_synced': 'Synced',
      'image_pending': 'Pending sync',
      'delete_image_confirm': 'Delete this image?',
      'image_note_optional': 'Note (optional)',
      'sync_images_lan_only': 'Images sync over local Wi-Fi only',
      // ── Status badges ──
      'status_completed': 'Completed',
      'status_paid': 'Paid',
      'status_scheduled': 'Scheduled',
      'status_partial': 'Partial',
      'status_unpaid': 'Unpaid',
      'status_postponed': 'Postponed',
      'status_cancelled': 'Cancelled',
      'status_pending': 'Pending',
      // ── Home / navigation ──
      'nav_dashboard': 'Dashboard',
      'nav_patients': 'Patients',
      'nav_financial': 'Financial',
      'nav_reports': 'Reports',
      'settings': 'Settings',
      'switch_to_light': 'Switch to light mode',
      'switch_to_dark': 'Switch to dark mode',
      'renew_by_prefix': 'Renew on the clinic desktop by ',
      'dismiss': 'Dismiss',
      'view_only_renew': 'View only — ask the clinic to renew',
      'activate_on_desktop_title': 'Activate on the desktop first',
      'activate_on_desktop_body':
          'Open the dental clinic desktop app and complete activation.',
      // ── Dashboard ──
      'total_patients': 'Total Patients',
      'todays_appointments': "Today's Appointments",
      'total_visits': 'Total Visits',
      'revenue': 'Revenue',
      'recent_appointments': 'Recent Appointments',
      'no_appointments_yet': 'No appointments yet.\nSchedule one to get started.',
      // ── Patients ──
      'search_patients_hint': 'Search by name, phone, or email…',
      'no_patients_found': 'No patients found',
      'add_patient': 'Add Patient',
      'delete_patient': 'Delete Patient',
      'cannot_be_undone': 'This cannot be undone.',
      'unable_to_load_patients': 'Unable to load patients right now',
      'possible_duplicate': 'Possible duplicate',
      'duplicate_exists_prefix': 'A patient with the same ',
      'duplicate_exists_suffix': ' already exists. Save anyway?',
      'dup_reason_phone': 'phone',
      'dup_reason_name': 'name',
      'save_anyway': 'Save anyway',
      'email': 'Email',
      'date_of_birth': 'Date of Birth',
      'tap_to_pick_date': 'Tap to pick date',
      'enter_valid_date': 'Enter a valid date',
      'address': 'Address',
      'save_patient': 'Save Patient',
      'required': 'Required',
      // ── Payment history ──
      'payments': 'Payments',
      'no_payments_recorded': 'No payments recorded yet',
      'followup': 'Follow-up',
      'billing': 'Billing',
      'billing_record': 'Billing record',
      'credit': 'credit',
      'total_collected': 'Total Collected',
      // ── Reports ──
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'no_data_yet': 'No data yet',
      'distinct_teeth': 'Distinct Teeth',
      'expenses': 'Expenses',
      'profit': 'Profit',
      'last_6_months': 'Last 6 Months',
      'latest_prefix': 'Latest: ',
      // ── Financial ──
      'receivables': 'Receivables',
      'unable_to_load_billing': 'Unable to load billing records right now',
      'billing_saved': 'Billing record saved',
      'billing_deleted': 'Billing record deleted',
      'delete_billing': 'Delete billing record',
      'delete_billing_q': 'Delete this billing record?',
      'delete_billing_credit_prefix': 'This also returns ',
      'delete_billing_credit_suffix':
          ' of applied credit to the patient. Delete this billing record?',
      'add_billing': 'Add Billing',
      'billed': 'Billed',
      'open': 'Open',
      'search_billing': 'Search billing records',
      'all': 'All',
      'no_billing_records': 'No billing records yet',
      'no_records_match': 'No records match your filters',
      'add_record': 'Add Record',
      'no_payment_date': 'No payment date',
      'credit_applied': 'Credit applied',
      'today': 'Today',
      'month': 'Month',
      'total_expenses': 'Total Expenses',
      'no_expenses_found': 'No expenses found',
      'add_expense': 'Add Expense',
      'no_outstanding': 'No outstanding balances',
      'total_receivables': 'Total Receivables',
      'patients_label': 'patients',
      'total': 'Total',
      'last_payment': 'Last payment',
      'amount': 'Amount',
      'amount_paid': 'Amount Paid',
      'use_credit': 'Use Credit',
      'available': 'Available',
      'payment_method': 'Payment Method',
      'method_cash': 'Cash',
      'method_card': 'Card',
      'method_bank_transfer': 'Bank Transfer',
      'method_insurance': 'Insurance',
      'category': 'Category',
      'vendor_optional': 'Vendor (optional)',
      'save_expense': 'Save Expense',
    }
  };

  static String t(String key, {bool isArabic = false}) {
    final lang = isArabic ? 'ar' : 'en';
    return translations[lang]?[key] ?? key;
  }
}
