"""Generate web_assets.py: base64 @font-face CSS + inline Phosphor icon sprite.

Run once (needs network) whenever fonts/icons change:
    python tools/gen_web_assets.py
The OUTPUT (web_assets.py) is committed; runtime never hits the network.
"""
from __future__ import annotations
import base64, re, sys, urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "web_assets.py"

# (family, weights) — must match the weights used in the shell.
FONTS = [("Manrope", [400, 500, 600, 700, 800]), ("Space+Grotesk", [500, 600, 700])]
GF_CSS = "https://fonts.googleapis.com/css2?family={fam}:wght@{wts}&display=swap"
# A modern Chrome UA makes Google serve woff2 (the WebView2/Chromium runtime).
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

PHOSPHOR_VER = "2.1.1"
CORE = f"https://unpkg.com/@phosphor-icons/core@{PHOSPHOR_VER}/assets"
ICONS = ["house", "users", "calendar-dots", "receipt", "gear", "magnifying-glass",
         "bell", "caret-down", "moon", "sun", "sign-out", "user", "user-plus",
         # added in Task 5 to cover the real shell's nav (Reports, Catalog):
         "chart-bar", "folders",
         # Post Studio nav icon (was added to the shipped web_assets.py without
         # ever landing in this generator's list — restored here so a re-run
         # doesn't silently drop it):
         "image",
         # Depo (inventory) gets its own icon instead of reusing Catalog's "folders":
         "package"]
FILL_ICONS = ["house"]  # active-item only

def _get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()

def build_font_css() -> str:
    blocks = []
    for fam, weights in FONTS:
        css = _get(GF_CSS.format(fam=fam, wts=";".join(map(str, weights)))).decode()
        # Keep only latin @font-face blocks; inline their woff2 as data URIs.
        for m in re.finditer(r"/\*\s*latin\s*\*/\s*(@font-face\s*{[^}]+})", css):
            block = m.group(1)
            url_m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not url_m:
                continue
            b64 = base64.b64encode(_get(url_m.group(1))).decode()
            data_uri = f"url(data:font/woff2;base64,{b64}) format('woff2')"
            blocks.append(re.sub(r"url\([^)]+\)\s*format\('woff2'\)", data_uri, block))
    return "\n".join(blocks)

def build_sprite() -> str:
    symbols = []
    def fetch_inner(weight: str, name: str) -> str:
        suffix = "" if weight == "regular" else f"-{weight}"
        svg = _get(f"{CORE}/{weight}/{name}{suffix}.svg").decode()
        inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1).strip()
        if "<path" not in inner:
            raise SystemExit(f"FAIL: {weight}/{name} produced no <path>")
        return inner
    for name in ICONS:
        symbols.append(f'<symbol id="i-{name}" viewBox="0 0 256 256">{fetch_inner("regular", name)}</symbol>')
    for name in FILL_ICONS:
        symbols.append(f'<symbol id="i-{name}-fill" viewBox="0 0 256 256">{fetch_inner("fill", name)}</symbol>')
    return ('<svg width="0" height="0" style="position:absolute" aria-hidden="true">'
            + "".join(symbols) + "</svg>")

def main() -> None:
    font_css = build_font_css()
    sprite = build_sprite()
    names = ICONS
    body = (
        '"""GENERATED by tools/gen_web_assets.py — do not edit by hand."""\n\n'
        f"ICON_NAMES = {tuple(names)!r}\n\n"
        f"FONT_FACE_CSS = {font_css!r}\n\n"
        f"ICON_SPRITE = {sprite!r}\n\n"
        "def render_icon(name, fill=False):\n"
        '    """Return <svg><use/></svg> markup referencing the inline sprite."""\n'
        "    ref = f'#i-{name}-fill' if fill else f'#i-{name}'\n"
        "    cls = 'ic ic-fill' if fill else 'ic'\n"
        '    return f\'<svg class="{cls}" aria-hidden="true"><use href="{ref}"/></svg>\'\n'
    )
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT} ({len(font_css)} B css, {len(names)} icons)")

if __name__ == "__main__":
    sys.exit(main())
