"""Generate static/post_studio/fonts.js from the in-repo TTFs (base64 @font-face).
Run once (and whenever the font files change): python tools/gen_post_studio_fonts.py
The generated fonts.js is committed; this script exists for reproducibility."""
import base64
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
FONTS = ROOT / "fonts"
OUT = ROOT / "static" / "post_studio" / "fonts.js"

# (css family, weight, filename)
FACES = [
    ("Manrope", 400, "Manrope-Regular.ttf"),
    ("Manrope", 700, "Manrope-Bold.ttf"),
    ("Manrope", 800, "Manrope-ExtraBold.ttf"),
    ("Playfair Display", 700, "PlayfairDisplay-Bold.ttf"),
    ("Cairo", 400, "Cairo-Regular.ttf"),
    ("Cairo", 700, "Cairo-Bold.ttf"),
]


def _face(family: str, weight: int, fname: str) -> str:
    b64 = base64.b64encode((FONTS / fname).read_bytes()).decode("ascii")
    return (
        "@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
        "font-display:swap;src:url(data:font/ttf;base64,%s) format('truetype');}"
        % (family, weight, b64)
    )


def main() -> None:
    css = "\n".join(_face(*f) for f in FACES)
    assert "`" not in css and "${" not in css, "css would break the JS template literal"
    js = (
        "// fonts.js — curated offline font bundle for Post Studio (base64 @font-face).\n"
        "// GENERATED by tools/gen_post_studio_fonts.py from fonts/*.ttf — do not hand-edit.\n"
        "export const FONT_FACE_CSS = `" + css + "`;\n\n"
        "export const FONT_OPTIONS = [\n"
        "  { id: 'manrope', label: 'Manrope', label_ar: 'مانروب', family: 'Manrope' },\n"
        "  { id: 'playfair', label: 'Playfair', label_ar: 'بلايفير', family: 'Playfair Display' },\n"
        "  { id: 'cairo', label: 'Cairo', label_ar: 'القاهرة', family: 'Cairo' },\n"
        "];\n\n"
        "let _injected = false;\n"
        "export function ensureFontsLoaded(doc = document) {\n"
        "  if (_injected || doc.getElementById('ps-font-faces')) { _injected = true; return; }\n"
        "  const style = doc.createElement('style');\n"
        "  style.id = 'ps-font-faces';\n"
        "  style.textContent = FONT_FACE_CSS;\n"
        "  (doc.head || doc.documentElement).appendChild(style);\n"
        "  _injected = true;\n"
        "}\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT} ({len(js)} bytes, {len(FACES)} faces)")


if __name__ == "__main__":
    main()
